

"use client"
import Input from "postcss/lib/input";
import { Image } from "react-bootstrap";


export default function Login(){

return(

    <>

<div className="justify-center
 items-center
 flex
 flex-col
  h-screen">


<img src="/todo3/public/login.png" height={500} width={400}></img>
   
    <div>
      
    <h1 className="mb-20 text-4xl">Login to Continue</h1>
    </div>
    

    <p className="text-2xl">Email</p>
    <input className="py-2 mb-7 text-black rounded px-4" placeholder="Email"></input>

    <p className="text-2xl">Password</p>
    <input className="py-2 mb-20 text-black rounded px-4" type="password"></input>
    <div>
    <button className="hover:animate-pulse hover:bg-slate-500 shadow-md shadow-white border border-white px-10 py-3 rounded-lg "> Login</button>
    </div>




    </div>
    </>
)


}

// Generated by CodiumAI

describe('Login', () => {

    // Tests that a login button is displayed
    it('should display a login button', () => {
        const wrapper = shallow(<Login />);
        expect(wrapper.find('button').length).toEqual(1);
    });
});
